name: Test PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev
      - name: Run tests
        run: |
          cd robohash
          go test -v ./...